#!/usr/bin/env bash
# configure a load-balancing server

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy

echo \
    "
frontend localnodes
    bind *:80
    mode http
    default_backend nodes
backend nodes
    mode http
    balance roundrobin
    server 2214-web-01 34.138.1.209
    server 2214-web-02 34.75.97.83" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart

