#!/usr/bin/env bash
# dsiplay hours from 0 to 12 display minutes from 1 to 59
h=0
min=1
while [ $h -le 12 ]
do
    echo "Hour: "$h
    while [ $min -le 59 ]
    do
	echo $min
	((min++))
    done
    min=1
    ((h++))
done