#!/usr/bin/env bash
# dsiplay hours from 0 to 12 display minutes from 1 to 59

i=0
while ((i < 12))
do
	j=1
	echo "Hour: $i"
		while ((j < 60))
		do
			echo "$j"
			j=$((j+1))
		done
		i=$((i+1))
done