#!/usr/bin/env bash
# dsiplay hours from 0 to 12 display minutes from 1 to 59

h=0
while ((h <= 12))
do
	min=1
	echo "Hour: $h"
	while((min < 60))
	do
		echo "$min"
		((min++))
	done
		((hour++))
done